version: '2'

volumes:
  data:
    driver_opts:
      device: ${PWD}/data
      type: none
      o: bind

services:
  xmpp_server:
    build: ../..
    image: unclev/prosody-docker-extended:experimental
    restart: unless-stopped
    ports:
      - '5222:5222'
      - '5269:5269'
      - '5347:5347'
      - '5280:5280'
      - '5281:5281'
      - '5380:80'
    volumes:
      - 'data:/var/lib/prosody'
      #- 'luarocks:/var/lib/prosody/.luarocks'

